"""add_path_file

Revision ID: 0fc184765176
Revises: 9ac3791ee579
Create Date: 2026-06-15 18:34:53.303684

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0fc184765176"
down_revision: Union[str, None] = "9ac3791ee579"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("massages", sa.Column("path", sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("massages", "path")
    # ### end Alembic commands ###
