"""add_password

Revision ID: 29c2cff198e5
Revises: 0fc184765176
Create Date: 2026-06-17 10:01:14.718207

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "29c2cff198e5"
down_revision: Union[str, None] = "0fc184765176"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("password", sa.String(length=100), nullable=False))
    op.create_unique_constraint(None, "users", ["password"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_column("users", "password")
    # ### end Alembic commands ###
